// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eleven-sh/aws-cloud-provider/userconfig (interfaces: ProfileLoader)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/aws/aws-sdk-go-v2/config"
	gomock "github.com/golang/mock/gomock"
)

// UserConfigProfileLoader is a mock of ProfileLoader interface.
type UserConfigProfileLoader struct {
	ctrl     *gomock.Controller
	recorder *UserConfigProfileLoaderMockRecorder
}

// UserConfigProfileLoaderMockRecorder is the mock recorder for UserConfigProfileLoader.
type UserConfigProfileLoaderMockRecorder struct {
	mock *UserConfigProfileLoader
}

// NewUserConfigProfileLoader creates a new mock instance.
func NewUserConfigProfileLoader(ctrl *gomock.Controller) *UserConfigProfileLoader {
	mock := &UserConfigProfileLoader{ctrl: ctrl}
	mock.recorder = &UserConfigProfileLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserConfigProfileLoader) EXPECT() *UserConfigProfileLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *UserConfigProfileLoader) Load(arg0, arg1, arg2 string) (config.SharedConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0, arg1, arg2)
	ret0, _ := ret[0].(config.SharedConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *UserConfigProfileLoaderMockRecorder) Load(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*UserConfigProfileLoader)(nil).Load), arg0, arg1, arg2)
}
