// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/eleven-sh/aws-cloud-provider/service (interfaces: UserConfigLoader)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	aws "github.com/aws/aws-sdk-go-v2/aws"
	userconfig "github.com/eleven-sh/aws-cloud-provider/userconfig"
	gomock "github.com/golang/mock/gomock"
)

// UserConfigLoader is a mock of UserConfigLoader interface.
type UserConfigLoader struct {
	ctrl     *gomock.Controller
	recorder *UserConfigLoaderMockRecorder
}

// UserConfigLoaderMockRecorder is the mock recorder for UserConfigLoader.
type UserConfigLoaderMockRecorder struct {
	mock *UserConfigLoader
}

// NewUserConfigLoader creates a new mock instance.
func NewUserConfigLoader(ctrl *gomock.Controller) *UserConfigLoader {
	mock := &UserConfigLoader{ctrl: ctrl}
	mock.recorder = &UserConfigLoaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *UserConfigLoader) EXPECT() *UserConfigLoaderMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *UserConfigLoader) Load(arg0 *userconfig.Config) (aws.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", arg0)
	ret0, _ := ret[0].(aws.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *UserConfigLoaderMockRecorder) Load(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*UserConfigLoader)(nil).Load), arg0)
}
